### ISSUE TITLE
Document changes from upstream

### ISSUE THREAD

**Issue by chmac** [abernix/standard-minifier-js#2]
What does this minifier change from upstream?

Switching to this minifier from upstream solved an issue where we saw memory usage on a production build jump to 3.5GB. It's back within the default node limit with this minifier, but we're not clear on what the underlying issue was nor what the change was that fixed the issue. Would be great to get some insight.

@abernix are you planning to keep this package updated in line with upstream? We've installed this on a client project, but I'm not sure if they should plan to switch back at some point, or whether your changes will eventually land upstream, etc...

**Comment by abernix** [comment]
No plans to maintain this long term. This uses `uglify-es` instead of `uglify-js`. The same change should be included in Meteor 1.6 (upcoming release) but please follow along with: https://github.com/meteor/meteor/issues/9075!  (And help test and report back feedback!) :smile:
